//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace View.Pages
{


    public partial class MedicoCadastro
    {

        protected System.Web.UI.HtmlControls.HtmlForm principal;

        protected System.Web.UI.WebControls.TextBox nome;

        protected System.Web.UI.WebControls.TextBox crm;

        protected System.Web.UI.WebControls.DropDownList idEspecialidade;

        protected System.Web.UI.WebControls.Label lblMensagem;
    }
}
